services:
  backup:
    build: .
    volumes:
      # volumes for dev
      - .:/workspace
    entrypoint: 
      - tail
      - -f
      - /dev/null
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"