version: '3'
set: [pipefail]

includes:
  databases:
    taskfile: "./databases/Taskfile.yml"
    internal: true
  storages:
    taskfile: "./storages/Taskfile.yml"
    internal: true

vars:
  BACKUP_ID:
    sh: |
      echo $(date '+%y-%m-%dt%H-%M-%Sz')_$(openssl rand -hex 5)
  BACKUP_DIR: "/data/{{ .BACKUP_ID }}"
  STORAGE_ENV_DIR: "/workspace/storage-env-files"

tasks:
  run:
    vars:
      list_valid_types: "postgresql edgedb kvrocks sealedSecrets"
      _pretty_list_valid_types:
        sh: |
          echo {{ .list_valid_types }} | sed "s/^/\'/; s/ /\', \'/g; s/$/\'/"
      list_storage_env_files:
        sh: "ls {{ .STORAGE_ENV_DIR }}"
          
    requires:
      vars:
        - DB_TYPE
    preconditions:
      - sh: |
          [[ "{{ .list_valid_types }}" =~ (^|[[:space:]]){{ .DB_TYPE }}($|[[:space:]]) ]]
        msg: "Invalid value for `DB_TYPE`: '{{ .DB_TYPE }}'. Expected one of: {{ ._pretty_list_valid_types }}."
    cmds:
      - mkdir -p {{ .BACKUP_DIR }}
      - defer: rm -rf {{ .BACKUP_DIR }}
      - task: "databases:{{ .DB_TYPE }}:backup"
      - for:
          var: list_storage_env_files
        task: storages:upload
        vars:
          STORAGE_ENV_FILE: '{{ .ITEM }}'