version: '3'

tasks:
  backup:
    requires:
      vars:
        - BACKUP_DIR
        - KUBE_SEALED_NAMESPACE
    cmds: 
      - |
        kubectl get -n {{ .KUBE_SEALED_NAMESPACE }} secret -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml \
           > {{ .BACKUP_DIR }}/sealed-secrets-keys.yaml