apiVersion: v1
entries:
  helloworld:
    - apiVersion: v2
      name: helloworld
      version: 0.1.0
      appVersion: 1.16.0
      description: A Helm chart for Kubernetes
      digest: 562eb251eae798bdaac098e05597d0258b1a513fa6206083cef237e66a93c7d8
      urls:
        - oci://ghcr.io/kevinlee-gh/packages/helm/helloworld/0.1.0
generated: "2025-06-09T14:14:48.042030438+07:00"
