services: 
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint:
      - tail
      - -f
      - /dev/null
    volumes:
      - runner_data:/workspace

volumes:
  runner_data: 