name: Build and Push Helm Charts

on:
  workflow_call:
    inputs:
      chart:
        description: 'The name of the Helm chart to build and push'
        required: true
        type: string

jobs: 
  build-and-push-helm:
    name: Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to GitHub Container Registry
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Chart
        id: package-chart
        run: |
          if [ "$(helm show chart helm/${{ inputs.chart }} | yq '.name')" != "${{ inputs.chart }}" ]; then
            echo "Chart name mismatch: expected ${{ inputs.chart }}, got $(helm show chart helm/${{ inputs.chart }} | yq '.name')"
            exit 1
          fi

          chart_version=$(yq '.version' helm/${{ inputs.chart }}/Chart.yaml)
          if [ "${{ github.ref_name }}" == "main" ]; then
            index_file="docs/charts/stable/index.yaml"
          else
            index_file="docs/charts/dev/index.yaml"
            chart_version="${chart_version}-${{ github.ref_name }}-${{ github.run_id }}"
          fi
          if [ -n "$(yq '.entries.${{ inputs.chart }}[] | select( .version == "${chart_version}" ) ' ${index_file})" ]; then
            echo "Chart ${{ inputs.chart }} with version ${chart_version} already exists in ${index_file}!"
            exit 1
          fi 

          helm package helm/${{ inputs.chart }} --destination ./tmp/ --version ${chart_version}
          
          echo "index_file=${index_file}" >> $GITHUB_OUTPUT
          echo "chart_version=${chart_version}" >> $GITHUB_OUTPUT
          echo "chart_appVersion=$(helm show chart helm/${{ inputs.chart }} | yq '.appVersion')" >> $GITHUB_OUTPUT
          echo "chart_description=$(helm show chart helm/${{ inputs.chart }} | yq '.description')" >> $GITHUB_OUTPUT
          echo "chart_url=oci://ghcr.io/${{ github.repository }}/helm/${{ inputs.chart }}/${chart_version}" >> $GITHUB_OUTPUT
          echo "chart_digest=$(sha256sum "./tmp/${{ inputs.chart }}-${chart_version}.tgz" | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Push Helm Chart to GitHub Container Registry
        run: |
          helm push ./tmp/${{ inputs.chart }}-${{ steps.package-chart.outputs.chart_version }}.tgz oci://ghcr.io/${{ github.repository }}/helm/

      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: main

      - name: Update Index YAML
        id: update-index
        run: |
          # Prepare new entry
          new_entry='{
            "apiVersion": "v2",
            "name": "${{ inputs.chart }}",
            "version": "${{ steps.package-chart.outputs.chart_version }}",
            "appVersion": "${{ steps.package-chart.outputs.chart_appVersion }}",
            "description": "${{ steps.package-chart.outputs.chart_description }}",
            "digest": "${{ steps.package-chart.outputs.chart_digest }}",
            "urls": [
              "${{ steps.package-chart.outputs.chart_url }}"
            ],
            "sources": [
              "https://github.com/${{ github.repository }}/tree/${{ github.sha }}/helm/${{ inputs.chart }}"
            ]
          }'

          # Append or create .entries.${chart_name}
          if yq e ".entries.${{ inputs.chart }}" "${{ steps.package-chart.outputs.index_file }}" > /dev/null; then
            # Append to existing list
            yq -i ".entries.${{ inputs.chart }} += [${new_entry}]" "${{ steps.package-chart.outputs.index_file }}"
          else
            # Create new list with the entry
            yq -i ".entries.${{ inputs.chart }} = [${new_entry}]" "${{ steps.package-chart.outputs.index_file }}"
          fi

          yq -i '.generated = now' "${{ steps.package-chart.outputs.index_file }}"

      - name: Commit and Push Index YAML
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add ${{ steps.package-chart.outputs.index_file }}
          git commit -m "Update ${{ steps.package-chart.outputs.index_file }}: ${{ inputs.chart }} - ${{ steps.package-chart.outputs.chart_version }}"
          git push origin main
