name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [helloworld]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env
        run: |
          echo "SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
      
      - name: Build Docker Image
        run:
          docker build -t ghcr.io/${{ github.repository }}:${{ github.base_ref }}-${{ env.SHORT_SHA }} ./docker/{{ matrix.image }}

      # Push the Docker image to the registry
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}:dev-${{ env.SHORT_SHA }}
