name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  changed-files:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

  image-matrix:
    name: Check image
    runs-on: ubuntu-latest
    needs: changed-files
    env: 
      changed_files: ${{ needs.changed-files.outputs.changed_files }}
    outputs:
      images: ${{ steps.get-changed-images.outputs.images }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get Changed Images
      id: get-changed-images
      run: |
        changed_images=$(echo ${changed_files} | tr ' ' '\n' | awk -F'/' '/^docker\// {print $2}' | sort -u)
        echo "images=${changed_images}" >> $GITHUB_OUTPUT
    - name: Debug Matrix
      run: |
        echo "Matrix: ${{ steps.get-changed-images.outputs.images }}"

  build-and-push-docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: image-matrix
    strategy:
      matrix: 
        image: ${{fromJson(needs.image-matrix.outputs.images)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env
        run: |
          export SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}/docker/${{ matrix.image }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        run:
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./docker/${{ matrix.image }}

      # Push the Docker image to the registry
      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 