name: Build and Push Docker Images

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  check-diff:
    name: Check diff
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

  image-matrix:
    name: Check image
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-image-matrix.outputs.images }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - id: set-image-matrix
      name: Set Image Matrix
      run: |
        LS_IMAGE=$(ls ./docker)
        echo "images=$(echo $LS_IMAGE | tr -d '\n' | jq -Rsc 'split(" ")')" >> $GITHUB_OUTPUT
    - name: Debug Matrix
      run: |
        echo "Matrix: ${{ steps.set-image-matrix.outputs.images }}"

  build-and-push-docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: image-matrix
    strategy:
      matrix: 
        image: ${{fromJson(needs.image-matrix.outputs.images)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup env
        run: |
          export SHORT_SHA=$(git rev-parse --short ${{ github.sha }})
          echo "IMAGE_NAME=ghcr.io/${{ github.repository }}/docker/${{ matrix.image }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.ref_name }}-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build Docker Image
        run:
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./docker/${{ matrix.image }}

      # Push the Docker image to the registry
      - name: Push Docker Image
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
 