name: Build and Push Helm Charts
on:
  push:
    branches:
      - main
      - dev

jobs: 
  changed-files:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

  helm-matrix:
    name: Check Helm Charts
    runs-on: ubuntu-latest
    needs: changed-files
    env: 
      changed_files: ${{ needs.changed-files.outputs.changed_files }}
    outputs:
      charts: ${{ steps.get-changed-charts.outputs.charts }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Changed Helm Charts
        id: get-changed-charts
        run: |
          changed_charts=$(echo ${changed_files} | tr ' ' '\n' | awk -F'/' '/^helm\// {print $2}' | sort -u)
          echo "charts=$(echo ${changed_charts} | tr -d '\n' | jq -Rsc 'split(" ")')" >> $GITHUB_OUTPUT

      - name: Debug Matrix
        run: |
          echo "Matrix: ${{ steps.get-changed-charts.outputs.charts }}"

  build-and-push-helm:
    name: Helm Charts
    runs-on: ubuntu-latest
    needs: helm-matrix
    strategy:
      matrix: 
        chart: ${{fromJson(needs.helm-matrix.outputs.charts)}}
    if: needs.helm-matrix.outputs.charts != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint Helm Charts
        run: helm --help

      - name: Login to GitHub Container Registry
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Charts
        run: |
          chart_name=${{ matrix.chart }}
          helm package helm/${{ matrix.chart }} --destination ./tmp/
      
      - name: Push Helm Charts to GitHub Container Registry
        run: |
          helm push ./tmp/${{ matrix.chart }}-*.tgz oci://ghcr.io/${{ github.repository }}/helm/${{ matrix.chart }}

  update-index-yaml:
    name: Update Index YAML
    runs-on: ubuntu-latest
    # needs: build-and-push-helm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Check Helm Index
        run: |
          yq -r '.' docs/charts/dev/index.yaml
      # - name: Commit and Push Index YAML
      #   run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "GitHub Action"
      #     git add ./tmp/index.yaml
      #     git commit -m "Update Helm index.yaml"
      #     git push origin main


      # - name: Package Helm Charts
      #   run: helm package charts/

      # - name: Push Helm Charts to GitHub Pages
      #   uses: jakejarvis/gh-pages-deploy@v2.0.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./charts/
      #     branch: gh-pages
      #     commit_message: "Deploy Helm charts"