name: Build and Push Helm Charts
on:
  push:
    branches:
      - main
      - dev

jobs: 
  changed-files:
    name: Check changed files
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

  helm-matrix:
    name: Check Helm Charts
    runs-on: ubuntu-latest
    needs: changed-files
    env: 
      changed_files: ${{ needs.changed-files.outputs.changed_files }}
    outputs:
      charts: ${{ steps.get-changed-charts.outputs.charts }}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get Changed Helm Charts
        id: get-changed-charts
        run: |
          changed_charts=$(echo ${changed_files} | tr ' ' '\n' | awk -F'/' '/^helm\// {print $2}' | sort -u)
          echo "charts=$(echo ${changed_charts} | tr -d '\n' | jq -Rsc 'split(" ")')" >> $GITHUB_OUTPUT

      - name: Debug Matrix
        run: |
          echo "Matrix: ${{ steps.get-changed-charts.outputs.charts }}"

  build-and-push-helm:
    name: Helm Charts
    runs-on: ubuntu-latest
    needs: helm-matrix
    strategy:
      matrix: 
        chart: ${{fromJson(needs.helm-matrix.outputs.charts)}}
    if: needs.helm-matrix.outputs.charts != '[]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Lint Helm Charts
        run: helm --help

      - name: Login to GitHub Container Registry
        run: |
          helm registry login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Package Helm Charts
        run: |
          chart_name=${{ matrix.chart }}
          helm package helm/${{ matrix.chart }} --destination ./tmp/
      
      - name: Push Helm Charts to GitHub Container Registry
        run: |
          helm push ./tmp/${{ matrix.chart }}-*.tgz oci://ghcr.io/${{ github.repository }}/helm/

      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: main

      - name: Update Index YAML
        run: |
          chart_name=${{ matrix.chart }}
          chart_package=$(ls ./tmp/${chart_name}-*.tgz | head -n 1)
          index_file="docs/charts/dev/index.yaml"

          # Extract chart metadata
          chart_version=$(helm show chart "${chart_package}" | yq '.version')
          chart_appVersion=$(helm show chart "${chart_package}" | yq '.appVersion')
          chart_description=$(helm show chart "${chart_package}" | yq '.description')
          chart_digest=$(sha256sum "${chart_package}" | awk '{print $1}')
          chart_url="oci://ghcr.io/${GITHUB_REPOSITORY}/helm/${chart_name}/${chart_version}"

          # Prepare new entry
          new_entry="{
            \"apiVersion\": \"v2\",
            \"name\": \"${chart_name}\",
            \"version\": \"${chart_version}\",
            \"appVersion\": \"${chart_appVersion}\",
            \"description\": \"${chart_description}\",
            \"digest\": \"${chart_digest}\",
            \"urls\": [
              \"${chart_url}\"
            ]
          }"

          # Append or create .entries.${chart_name}
          if yq e ".entries.${chart_name}" "${index_file}" > /dev/null; then
            # Append to existing list
            yq -i ".entries.${chart_name} += [${new_entry}]" "${index_file}"
          else
            # Create new list with the entry
            yq -i ".entries.${chart_name} = [${new_entry}]" "${index_file}"
          fi

      - name: Commit and Push Index YAML
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add docs/charts/dev/index.yaml
          git commit -m "Update Helm index.yaml for ${{ matrix.chart }}"
          git push origin main
